# Site settings
title: wcong blog
email: wc19920415@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    hello world
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://wcong.github.io" # the base hostname & protocol for your site
twitter_username: wcong2 
github_username:  wcong

# Build settings
# remember rdiscount is the normal markdown
markdown: rdiscount 
