# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8
# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"
# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false
# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"
# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null
# Site settings
title: wcong blog
email: wc19920415@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    hello world
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://wcong.github.io" # the base hostname & protocol for your site
twitter_username: wcong2 
github_username:  wcong
feed: /atom.xml

# Build settings
# remember rdiscount is the normal markdown
markdown: rdiscount 

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 邮件
    url: mailto:wc19920415@gmail.com
    icon: icon-envelope-alt
    class: none
  - text: twitter
    url: https://twitter.com/wcong2
    icon: icon-twitter
    class: none
  - text: github
    url: https://github.com/wcong
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: wcong
