# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://wcong.github.io
date_format: "ordinal"
title: wcong
subtitle: "wcong"
description: "wcong"
keywords: wcong
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: wcong
organization: wcong.org
organization_url: http://wcong.github.io
github_username: wcong
location: Hangzhou, China
email: wc19920415@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: Category

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Links

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: wcong/wcong.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, netease_gentie, gitment
comments_provider: gitment
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: wcong
    repo: wcong.github.io
    oauth:
        client_id: 7f27c12f5d2fdc3a1857
        client_secret: c662abf171494ac488f2969333e82c29046a7b5a

lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-103107514-1
